name: Anti Mouse CI/CD and Release

permissions:
  contents: write
  pull-requests: write

on: [ push ]

#on:
#  push:
#    tags:
#      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Устанавливаем ЖДК
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Наливаем "Сбитень"
        uses: sbt/setup-sbt@v1

      - name: Освобождаем мышь
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Создаём универсальный пакет
        run: sbt "Universal / packageBin"

      - name: Определяем ФИО
        run: |
          BIN_FILE=$(ls ./target/universal/anti-mouse-*.zip | head -n 1)
          echo "BIN_FILE=$BIN_FILE" >> $GITHUB_ENV
          echo "PACKAGE_ASSET_FILE=$(basename $BIN_FILE)" >> $GITHUB_ENV
          echo "Found package file: $BIN_FILE"
        shell: bash

      - name: Загружаем мышеловку
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BIN_FILE }}
          asset_name: ${{ env.PACKAGE_ASSET_FILE }}
          asset_content_type: application/zip
